target: all,overrides-exporter

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: mimir
      secret_access_key: supersecret
      insecure: true
      bucket_name: mimir

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

memberlist:
  join_members: [mimir-1, mimir-2, mimir-3]

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_api: true
  rule_path: /data/ruler
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    kvstore:
      store: inmemory

ruler_storage:
  backend: local
  local:
    directory: /etc/alertmanager
