global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert-rules.yaml

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "node-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "node-exporter:9100"

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "loki:3100"

  - job_name: "cortex"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "cortex:9010"

  - job_name: "mimir"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "mimir-1:8080"
          - "mimir-2:8080"
          - "mimir-3:8080"

remote_write:
  - url: http://cortex:9010/api/v1/push
    headers:
      X-Scope-OrgID: fake
  - url: http://mimir:9009/api/v1/push
    headers:
      X-Scope-OrgID: fake
