global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert-rules.yaml

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: "node-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "node-exporter:9100"
